// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_uat.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSpsXp3YF7PfoB2gmnvdnHbGodbETMAr0',
    appId: '1:136369635094:web:eb334ba8c2cc901c911a37',
    messagingSenderId: '136369635094',
    projectId: 'easy-pay-uat',
    authDomain: 'easy-pay-uat.firebaseapp.com',
    storageBucket: 'easy-pay-uat.firebasestorage.app',
    measurementId: 'G-PEGKVSZ4RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEUbIaKPwWogvJ6qVhRgc6Rpbpe4kvYC4',
    appId: '1:136369635094:android:01fa1ab34607804f911a37',
    messagingSenderId: '136369635094',
    projectId: 'easy-pay-uat',
    storageBucket: 'easy-pay-uat.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkmJWm7nv0YByo0p1KYaa2f7GO02uzm4g',
    appId: '1:136369635094:ios:8ad319fea1a9c405911a37',
    messagingSenderId: '136369635094',
    projectId: 'easy-pay-uat',
    storageBucket: 'easy-pay-uat.firebasestorage.app',
    iosBundleId: 'com.example.easyPayApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkmJWm7nv0YByo0p1KYaa2f7GO02uzm4g',
    appId: '1:136369635094:ios:8ad319fea1a9c405911a37',
    messagingSenderId: '136369635094',
    projectId: 'easy-pay-uat',
    storageBucket: 'easy-pay-uat.firebasestorage.app',
    iosBundleId: 'com.example.easyPayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSpsXp3YF7PfoB2gmnvdnHbGodbETMAr0',
    appId: '1:136369635094:web:e91526bdbb4cd734911a37',
    messagingSenderId: '136369635094',
    projectId: 'easy-pay-uat',
    authDomain: 'easy-pay-uat.firebaseapp.com',
    storageBucket: 'easy-pay-uat.firebasestorage.app',
    measurementId: 'G-2WL5TR4TGC',
  );
}
