// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxg-8gMM0doo-3a4P39J3bMpqcR1FHOj4',
    appId: '1:767746412356:web:6e2100b6681a3cc057d111',
    messagingSenderId: '767746412356',
    projectId: 'easy-pay-5a55e',
    authDomain: 'easy-pay-5a55e.firebaseapp.com',
    storageBucket: 'easy-pay-5a55e.firebasestorage.app',
    measurementId: 'G-8NX7J3F2LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd2FKWKo0JTdRCTVJ9LCf7YNhe_23zImU',
    appId: '1:767746412356:android:3f29982abfd5c77c57d111',
    messagingSenderId: '767746412356',
    projectId: 'easy-pay-5a55e',
    storageBucket: 'easy-pay-5a55e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX4oX0WJPS-1kSbpES-gGq9rd7ppuE5LQ',
    appId: '1:767746412356:ios:69dbf0fb448a83b557d111',
    messagingSenderId: '767746412356',
    projectId: 'easy-pay-5a55e',
    storageBucket: 'easy-pay-5a55e.firebasestorage.app',
    iosBundleId: 'com.example.easyPayApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX4oX0WJPS-1kSbpES-gGq9rd7ppuE5LQ',
    appId: '1:767746412356:ios:69dbf0fb448a83b557d111',
    messagingSenderId: '767746412356',
    projectId: 'easy-pay-5a55e',
    storageBucket: 'easy-pay-5a55e.firebasestorage.app',
    iosBundleId: 'com.example.easyPayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxg-8gMM0doo-3a4P39J3bMpqcR1FHOj4',
    appId: '1:767746412356:web:114479af6ba9063957d111',
    messagingSenderId: '767746412356',
    projectId: 'easy-pay-5a55e',
    authDomain: 'easy-pay-5a55e.firebaseapp.com',
    storageBucket: 'easy-pay-5a55e.firebasestorage.app',
    measurementId: 'G-9GG0S7B62S',
  );
}
