// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUjgnJbxJrX-5oBn-qXa37_cD_iRjFMZo',
    appId: '1:561507158686:web:62bfbfca45cec5e7d5498f',
    messagingSenderId: '561507158686',
    projectId: 'easy-pay-prod',
    authDomain: 'easy-pay-prod.firebaseapp.com',
    storageBucket: 'easy-pay-prod.firebasestorage.app',
    measurementId: 'G-140GRD85Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5SICcgNQ6P4Tmh9CZwvinaseUj9PZ3ok',
    appId: '1:561507158686:android:72a51244beba30f4d5498f',
    messagingSenderId: '561507158686',
    projectId: 'easy-pay-prod',
    storageBucket: 'easy-pay-prod.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh3pvXDLMb9Bw2T2SadBOnQ7yg6kfmEM8',
    appId: '1:561507158686:ios:5fd3b84105ac72e7d5498f',
    messagingSenderId: '561507158686',
    projectId: 'easy-pay-prod',
    storageBucket: 'easy-pay-prod.firebasestorage.app',
    iosBundleId: 'com.example.easyPayApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh3pvXDLMb9Bw2T2SadBOnQ7yg6kfmEM8',
    appId: '1:561507158686:ios:5fd3b84105ac72e7d5498f',
    messagingSenderId: '561507158686',
    projectId: 'easy-pay-prod',
    storageBucket: 'easy-pay-prod.firebasestorage.app',
    iosBundleId: 'com.example.easyPayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUjgnJbxJrX-5oBn-qXa37_cD_iRjFMZo',
    appId: '1:561507158686:web:9b4997e500f25461d5498f',
    messagingSenderId: '561507158686',
    projectId: 'easy-pay-prod',
    authDomain: 'easy-pay-prod.firebaseapp.com',
    storageBucket: 'easy-pay-prod.firebasestorage.app',
    measurementId: 'G-V5NRRRRGSF',
  );
}
