name: easy_pay_app
description: "EasyPay - Simple & fast payment app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/onboarding_balance.png
    - assets/images/onboarding_success.png
    - assets/images/onboarding_cards.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
