// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:easy_pay_app/core/config/app_config.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => currentPlatformFor(AppEnvironment.prod);

  static FirebaseOptions currentPlatformFor(AppEnvironment environment) {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        switch (environment) {
          case AppEnvironment.dev:
            return androidDev;
          case AppEnvironment.staging:
            return androidStaging;
          case AppEnvironment.prod:
            return androidProd;
        }
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH5tzGEESHGx652WSMHSDoPXZxfMu78Nk',
    appId: '1:357833632037:web:3d0657cd157d4a364812cc',
    messagingSenderId: '357833632037',
    projectId: 'easypay-e6ffb',
    authDomain: 'easypay-e6ffb.firebaseapp.com',
    storageBucket: 'easypay-e6ffb.firebasestorage.app',
    measurementId: 'G-CZ4RHQJ5W5',
  );

  static const FirebaseOptions android = androidProd;

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyAnaRKOBZJErHaIrJ7RMi2V9VxyM_v0Cuw',
    appId: '1:357833632037:android:c9396d37752750504812cc',
    messagingSenderId: '357833632037',
    projectId: 'easypay-e6ffb',
    storageBucket: 'easypay-e6ffb.firebasestorage.app',
  );

  static const FirebaseOptions androidStaging = FirebaseOptions(
    apiKey: 'AIzaSyAnaRKOBZJErHaIrJ7RMi2V9VxyM_v0Cuw',
    appId: '1:357833632037:android:16b19dda693b57a24812cc',
    messagingSenderId: '357833632037',
    projectId: 'easypay-e6ffb',
    storageBucket: 'easypay-e6ffb.firebasestorage.app',
  );

  static const FirebaseOptions androidProd = FirebaseOptions(
    apiKey: 'AIzaSyAnaRKOBZJErHaIrJ7RMi2V9VxyM_v0Cuw',
    appId: '1:357833632037:android:a6fe9bca3d69cb544812cc',
    messagingSenderId: '357833632037',
    projectId: 'easypay-e6ffb',
    storageBucket: 'easypay-e6ffb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKCR8tzZL2UHhcQaBg1Y3qB_ZxDMfIidk',
    appId: '1:357833632037:ios:ec772a1cf39e409a4812cc',
    messagingSenderId: '357833632037',
    projectId: 'easypay-e6ffb',
    storageBucket: 'easypay-e6ffb.firebasestorage.app',
    iosBundleId: 'com.example.easyPayApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKCR8tzZL2UHhcQaBg1Y3qB_ZxDMfIidk',
    appId: '1:357833632037:ios:ec772a1cf39e409a4812cc',
    messagingSenderId: '357833632037',
    projectId: 'easypay-e6ffb',
    storageBucket: 'easypay-e6ffb.firebasestorage.app',
    iosBundleId: 'com.example.easyPayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH5tzGEESHGx652WSMHSDoPXZxfMu78Nk',
    appId: '1:357833632037:web:86c9c555b72c0dc74812cc',
    messagingSenderId: '357833632037',
    projectId: 'easypay-e6ffb',
    authDomain: 'easypay-e6ffb.firebaseapp.com',
    storageBucket: 'easypay-e6ffb.firebasestorage.app',
    measurementId: 'G-BWLLW23MRN',
  );
}
